# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# .goreleaser.yml

version: 2

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

before:
  hooks:
    - go mod tidy
    - rm -rf completions
    - mkdir completions
    - rm -rf manpages
    - mkdir manpages
    - sh -c 'go run ./cmd/thinkt completion bash > ./completions/thinkt.bash'
    - sh -c 'go run ./cmd/thinkt completion fish > ./completions/thinkt.fish'
    - sh -c 'go run ./cmd/thinkt completion zsh > ./completions/thinkt.zsh'
    - sh -c 'go run ./cmd/thinkt docs man -o ./manpages/'

builds:
  - id: linux-amd64
    main: ./cmd/thinkt
    binary: thinkt
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    ldflags:
      - -s -w

  - id: linux-arm64
    main: ./cmd/thinkt
    binary: thinkt
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    ldflags:
      - -s -w

  - id: darwin-amd64
    main: ./cmd/thinkt
    binary: thinkt
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - MACOSX_DEPLOYMENT_TARGET=11.0
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    ldflags:
      - -s -w

  - id: darwin-arm64
    main: ./cmd/thinkt
    binary: thinkt
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - MACOSX_DEPLOYMENT_TARGET=11.0
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
    ldflags:
      - -s -w

  # - id: windows-amd64
  #   main: ./cmd/thinkt
  #   binary: thinkt
  #   goos:
  #     - windows
  #   goarch:
  #     - amd64
  #   env:
  #     - CGO_ENABLED=1
  #     - CC=x86_64-w64-mingw32-gcc-posix
  #     - CXX=x86_64-w64-mingw32-g++-posix
  #   ldflags:
  #     - -s -w
  #     - -extldflags "-static -static-libgcc -static-libstdc++ -lpthread -lucrt"

archives:
  - id: default
    ids:
      - linux-amd64
      - linux-arm64
      - darwin-amd64
      - darwin-arm64
      # - windows-amd64
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - src: ./manpages/*
        dst: man/man1/
        strip_parent: true
      - src: ./completions/*
        dst: completions/
        strip_parent: true

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      ids:
        - thinkt
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"
        wait: true
        timeout: 20m

homebrew_casks:
  - name: thinkt
    url:
      verified: github.com/wethinkt/go-thinkt
    repository:
      owner: wethinkt
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/wethinkt/go-thinkt
    description: Tools for exploring LLM conversation traces
    license: MIT
    binaries:
      - thinkt
    manpages:
      - man/man1/thinkt.1
    completions:
      bash: completions/thinkt.bash
      zsh: completions/thinkt.zsh
      fish: completions/thinkt.fish

dockers:
  - id: linux-amd64
    ids:
      - linux-amd64
    dockerfile: etc/Dockerfile.goreleaser
    image_templates:
      - "ghcr.io/wethinkt/thinkt:{{ .Version }}-amd64"
      - "ghcr.io/wethinkt/thinkt:latest-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title=thinkt"
      - "--label=org.opencontainers.image.description=Tools for exploring LLM conversation traces"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
    use: buildx

  - id: linux-arm64
    ids:
      - linux-arm64
    dockerfile: etc/Dockerfile.goreleaser
    image_templates:
      - "ghcr.io/wethinkt/thinkt:{{ .Version }}-arm64"
      - "ghcr.io/wethinkt/thinkt:latest-arm64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title=thinkt"
      - "--label=org.opencontainers.image.description=Tools for exploring LLM conversation traces"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
    use: buildx
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/wethinkt/thinkt:{{ .Version }}"
    image_templates:
      - "ghcr.io/wethinkt/thinkt:{{ .Version }}-amd64"
      - "ghcr.io/wethinkt/thinkt:{{ .Version }}-arm64"

  - name_template: "ghcr.io/wethinkt/thinkt:latest"
    image_templates:
      - "ghcr.io/wethinkt/thinkt:latest-amd64"
      - "ghcr.io/wethinkt/thinkt:latest-arm64"
