# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# .goreleaser.yml

version: 2

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

before:
  hooks:
    - go mod tidy
    - rm -rf completions
    - mkdir completions
    - rm -rf manpages
    - mkdir manpages
    - sh -c 'go run ./cmd/thinkt completion bash > ./completions/thinkt.bash'
    - sh -c 'go run ./cmd/thinkt completion fish > ./completions/thinkt.fish'
    - sh -c 'go run ./cmd/thinkt completion zsh > ./completions/thinkt.zsh'
    - sh -c 'go run ./cmd/thinkt docs man -o ./manpages/'

builds:
  - id: default
    main: ./cmd/thinkt
    binary: thinkt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/wethinkt/go-thinkt/internal/version.Version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - src: ./manpages/*
        dst: man/man1/
        strip_parent: true
      - src: ./completions/*
        dst: completions/
        strip_parent: true

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      ids:
        - default
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"
        wait: true
        timeout: 20m

homebrew_casks:
  - name: thinkt
    url:
      verified: github.com/wethinkt/go-thinkt
    repository:
      owner: wethinkt
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/wethinkt/go-thinkt
    description: Tools for exploring LLM conversation traces
    license: MIT
    binaries:
      - thinkt
    completions:
      bash: completions/thinkt.bash
      zsh: completions/thinkt.zsh
      fish: completions/thinkt.fish
    manpages:
      - man/man1/thinkt-completion-bash.1
      - man/man1/thinkt-completion-fish.1
      - man/man1/thinkt-completion-powershell.1
      - man/man1/thinkt-completion-zsh.1
      - man/man1/thinkt-completion.1
      - man/man1/thinkt-docs-man.1
      - man/man1/thinkt-docs-markdown.1
      - man/man1/thinkt-docs.1
      - man/man1/thinkt-indexer.1
      - man/man1/thinkt-projects-copy.1
      - man/man1/thinkt-projects-delete.1
      - man/man1/thinkt-projects-list.1
      - man/man1/thinkt-projects-summary.1
      - man/man1/thinkt-projects-tree.1
      - man/man1/thinkt-projects-view.1
      - man/man1/thinkt-projects.1
      - man/man1/thinkt-prompts-extract.1
      - man/man1/thinkt-prompts-info.1
      - man/man1/thinkt-prompts-list.1
      - man/man1/thinkt-prompts-templates.1
      - man/man1/thinkt-prompts.1
      - man/man1/thinkt-serve-fingerprint.1
      - man/man1/thinkt-serve-lite.1
      - man/man1/thinkt-serve-mcp.1
      - man/man1/thinkt-serve-token.1
      - man/man1/thinkt-serve.1
      - man/man1/thinkt-sessions-copy.1
      - man/man1/thinkt-sessions-delete.1
      - man/man1/thinkt-sessions-list.1
      - man/man1/thinkt-sessions-summary.1
      - man/man1/thinkt-sessions-view.1
      - man/man1/thinkt-sessions.1
      - man/man1/thinkt-sources-list.1
      - man/man1/thinkt-sources-status.1
      - man/man1/thinkt-sources.1
      - man/man1/thinkt-teams-list.1
      - man/man1/thinkt-teams.1
      - man/man1/thinkt-theme-builder.1
      - man/man1/thinkt-theme-list.1
      - man/man1/thinkt-theme-set.1
      - man/man1/thinkt-theme.1
      - man/man1/thinkt-tui.1
      - man/man1/thinkt-version.1
      - man/man1/thinkt.1

dockers:
  - id: linux-amd64
    ids:
      - default
    dockerfile: etc/Dockerfile.goreleaser
    image_templates:
      - "ghcr.io/wethinkt/thinkt:{{ .Version }}-amd64"
      - "ghcr.io/wethinkt/thinkt:latest-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title=thinkt"
      - "--label=org.opencontainers.image.description=Tools for exploring LLM conversation traces"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
    use: buildx

  - id: linux-arm64
    ids:
      - default
    dockerfile: etc/Dockerfile.goreleaser
    image_templates:
      - "ghcr.io/wethinkt/thinkt:{{ .Version }}-arm64"
      - "ghcr.io/wethinkt/thinkt:latest-arm64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title=thinkt"
      - "--label=org.opencontainers.image.description=Tools for exploring LLM conversation traces"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
    use: buildx
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/wethinkt/thinkt:{{ .Version }}"
    image_templates:
      - "ghcr.io/wethinkt/thinkt:{{ .Version }}-amd64"
      - "ghcr.io/wethinkt/thinkt:{{ .Version }}-arm64"

  - name_template: "ghcr.io/wethinkt/thinkt:latest"
    image_templates:
      - "ghcr.io/wethinkt/thinkt:latest-amd64"
      - "ghcr.io/wethinkt/thinkt:latest-arm64"
