# .goreleaser.yml

version: 2

partial:
  by: goos

before:
  hooks:
    - go mod tidy
    - go run ./cmd/thinkt docs man -o ./docs/man

builds:
  - id: thinkt
    main: ./cmd/thinkt
    binary: thinkt
    env:
      - CGO_ENABLED=1
    targets: [go_first_class]

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - src: ./docs/man/*
        dst: man/man1/
        strip_parent: true

checksum:
  name_template: checksums.txt
  split: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

homebrew_casks:
  - name: thinkt
    binaries:
      - thinkt
    repository:
      owner: wethinkt
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: https://github.com/wethinkt/go-thinkt
    description: CLI tools for exploring LLM conversation traces
