version: "3"

vars:
  BIN_DIR: ./bin

tasks:
  default:
    deps: [test, build]

  build:
    desc: Build the thinkt CLI
    deps: [go-tidy]
    sources:
      - ./cmd/thinkt/**/*.go
      - ./internal/**/*.go
      - go.mod
      - go.sum
    generates:
      - "{{.BIN_DIR}}/thinkt"
    cmds:
      - go build -o {{.BIN_DIR}}/thinkt ./cmd/thinkt

  test:
    desc: Run tests
    cmds:
      - go test ./...

  go-tidy:
    desc: Tidy Go modules
    cmds:
      - go mod tidy

  install:
    desc: Install thinkt to GOPATH/bin
    deps: [go-tidy]
    cmds:
      - go install ./cmd/thinkt

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run
