version: "3"

vars:
  BIN_DIR: ./bin

tasks:
  default:
    deps: [test, build]

  # Things we need to install to do dev work
  dev-deps:
    cmds:
      - go install "github.com/swaggo/swag/cmd/swag@v1.16.6"

  build:
    desc: Build the thinkt CLI
    deps: [go-tidy]
    sources:
      - ./cmd/thinkt/**/*.go
      - ./internal/**/*.go
      - ./internal/server/web-lite/**/*
      - go.mod
      - go.sum
    generates:
      - "{{.BIN_DIR}}/thinkt"
    cmds:
      - go build -o {{.BIN_DIR}}/thinkt ./cmd/thinkt

  test:
    desc: Run tests
    cmds:
      - go test ./...

  go-tidy:
    desc: Tidy Go modules
    deps: [server:swag-v2]
    cmds:
      - go mod tidy

  install:
    desc: Install thinkt to GOPATH/bin
    deps: [go-tidy]
    cmds:
      - go install ./cmd/thinkt

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  ###############################################################################
  # MCP Server
  ###############################################################################

  mcp:stdio-schema:
    desc: "Extracts the schema from the stdio server"
    deps: [build]
    cmds:
      - printf '{"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"test","version":"1.0"}},"jsonrpc":"2.0","id":1}\n{"method":"tools/list","params":{},"jsonrpc":"2.0","id":2}\n' | ./bin/thinkt serve mcp {{.CLI_ARGS}} 2>/dev/null
      - printf '{"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"test","version":"1.0"}},"jsonrpc":"2.0","id":1}\n{"method":"resources/list","params":{},"jsonrpc":"2.0","id":2}\n' | ./bin/thinkt serve mcp {{.CLI_ARGS}} 2>/dev/null

  mcp:stdio-schema-test:
    desc: "Extracts the schema from the stdio server without error suppression"
    deps: [build]
    cmds:
      - printf '{"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"test","version":"1.0"}},"jsonrpc":"2.0","id":1}\n{"method":"tools/list","params":{},"jsonrpc":"2.0","id":2}\n' | ./bin/thinkt serve mcp {{.CLI_ARGS}}
      - printf '{"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"test","version":"1.0"}},"jsonrpc":"2.0","id":1}\n{"method":"resources/list","params":{},"jsonrpc":"2.0","id":2}\n' | ./bin/thinkt serve mcp {{.CLI_ARGS}}

  ###############################################################################
  # OpenAPI 2.0 Swagger
  ###############################################################################

  server:swag-v2:
    dir: ./internal/server
    cmds:
      - swag init --parseDependency --parseDepth 2 -o ./docs -g ./api.go
    sources:
      - "*.go"
    generates:
      - ./docs/docs.go
      - ./docs/swagger.json
      - ./docs/swagger.yaml

  server:swag-clean:
    dir: ./internal/server/docs
    cmds:
      - rm -f docs.go swagger.json swagger.yaml

  ###############################################################################
  # Docker
  ###############################################################################

  docker:release:
    cmds:
      - |
        docker run --rm \
          -v $(pwd):/go/src/github.com/wethinkt/go-thinkt \
          -w /go/src/github.com/wethinkt/go-thinkt \
          ghcr.io/goreleaser/goreleaser-cross:v1.25.6 \
          build --snapshot --clean

  ###############################################################################
  # Documentation
  ###############################################################################

  docs:clean:
    desc: Cleans documentation pages
    deps:
      - docs:man:clean
      - docs:md:clean

  docs:man:build:
    desc: Generate man pages
    deps: [build]
    cmds:
      - ./bin/thinkt docs man -o docs/man -v
    sources:
      - ./cmd/thinkt/**/*.go
    generates:
      - docs/man/thinkt.1

  docs:man:clean:
    desc: Cleans manpages
    cmds:
      - rm -rf docs/man

  docs:md:build:
    desc: Generate hugo docs
    deps: [build]
    cmds:
      - ./bin/thinkt docs markdown --hugo -o docs/hugo/content/command -v
    sources:
      - ./cmd/thinkt/**/*.go
    generates:
      - docs/hugo/content/command/thinkt.md

  docs:md:clean:
    desc: Cleans markdown
    cmds:
      - rm -rf docs/hugo/content/command

  docs:hugo:serve:
    desc: Serve hugo docs server
    deps: [docs:md:build]
    dir: ./docs/hugo
    cmds:
      - hugo serve

  docs:hugo:build:
    desc: Build hugo docs
    deps: [docs:md:build]
    dir: ./docs/hugo
    cmds:
      - rm -rf public
      - hugo --minify

  ###############################################################################
  # Release
  ###############################################################################

  release:notarize:
    desc: Notarize the build
    deps: [build]
    cmds:
      - |
        if [ -z "$MACOS_CODESIGN_ID" ]; then
          echo "Error: MACOS_CODESIGN_ID env var not set"
          exit 1
        fi
      - codesign --force --options runtime -s "$MACOS_CODESIGN_ID" {{.BIN_DIR}}/thinkt
      - codesign -dv --verbose=4 {{.BIN_DIR}}/thinkt
      - ditto -c -k ./bin/thinkt thinkt.zip
      - xcrun notarytool submit thinkt.zip --key "$MACOS_NOTARY_KEY" --key-id "$MACOS_NOTARY_KEY_ID" --issuer "$MACOS_NOTARY_ISSUER_ID" --wait

  release:test:
    desc: Test release build with goreleaser (requires PRO key)
    cmds:
      - |
        if [ -z "$GORELEASER_KEY" ]; then
          echo "Error: GORELEASER_KEY env var not set"
          exit 1
        fi
      - goreleaser release --snapshot --clean --split

  release:merge:
    desc: Merge split release builds (requires PRO key)
    cmds:
      - |
        if [ -z "$GORELEASER_KEY" ]; then
          echo "Error: GORELEASER_KEY env var not set"
          exit 1
        fi
      - goreleaser continue --merge
