package cmd

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"charm.land/lipgloss/v2"
	"github.com/spf13/cobra"

	"github.com/wethinkt/go-thinkt/internal/cmd"
	"github.com/wethinkt/go-thinkt/internal/config"
	thinktI18n "github.com/wethinkt/go-thinkt/internal/i18n"
	indexer "github.com/wethinkt/go-thinkt/internal/indexer"
	"github.com/wethinkt/go-thinkt/internal/indexer/db"
	"github.com/wethinkt/go-thinkt/internal/indexer/rpc"
	"github.com/wethinkt/go-thinkt/internal/indexer/summarize"
	"github.com/wethinkt/go-thinkt/internal/tui"
	"github.com/wethinkt/go-thinkt/internal/tui/theme"
	"golang.org/x/term"
)

var summarizeCmd = &cobra.Command{
	Use:   "summarize",
	Short: "Manage summarization model, storage, and sync",
	Long: `Manage the summarization infrastructure: model selection, sync, and storage.

Use 'summarize list' to see available models.
Use 'summarize sync' to generate summaries for indexed sessions.
Use 'summarize status' to check model, download state, and progress.`,
	Args: cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		return summarizeListCmd.RunE(cmd, args)
	},
}

var summarizeListJSON bool

var summarizeListCmd = &cobra.Command{
	Use:   "list",
	Short: "List available summarization models",
	Args:  cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		cfg, err := config.Load()
		if err != nil {
			cfg = config.Default()
		}
		if summarizeListJSON {
			return printSummarizeModelListJSON(cfg.Summarization.Model)
		}
		printSummarizeModelList(cfg.Summarization.Model)
		return nil
	},
}

var summarizePurgeCmd = &cobra.Command{
	Use:   "purge",
	Short: "Remove summaries from previous models",
	Long:  "Deletes stale summaries that were generated by a model other than the currently configured one. This frees disk space without affecting current results.",
	Args:  cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		cfg, err := config.Load()
		if err != nil {
			cfg = config.Default()
		}
		activeModel := cfg.Summarization.Model
		activePath := db.SummariesPathForModel(sumDBDir, activeModel)

		files, err := filepath.Glob(filepath.Join(sumDBDir, "*.duckdb"))
		if err != nil {
			return fmt.Errorf("glob summaries dir: %w", err)
		}

		var purged int
		for _, f := range files {
			if filepath.Clean(f) == filepath.Clean(activePath) {
				continue
			}
			if err := os.Remove(f); err != nil {
				fmt.Fprint(os.Stderr, thinktI18n.Tf("indexer.summarize.purge.removeWarning", "warning: could not remove %s: %v\n", f, err))
			} else {
				purged++
				fmt.Print(thinktI18n.Tf("indexer.summarize.purge.removed", "Removed: %s\n", filepath.Base(f)))
			}
		}

		if purged == 0 {
			fmt.Println(thinktI18n.T("indexer.summarize.purge.noneFound", "No stale summary databases to purge."))
		} else {
			fmt.Print(thinktI18n.Tf("indexer.summarize.purge.complete", "Purged %d stale summary database(s).\n", purged))
		}
		return nil
	},
}

var summarizeEnableCmd = &cobra.Command{
	Use:   "enable",
	Short: "Enable summarization",
	Args:  cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		cfg, err := config.Load()
		if err != nil {
			cfg = config.Default()
		}
		if cfg.Summarization.Enabled {
			fmt.Print(thinktI18n.Tf("indexer.summarize.alreadyEnabled", "Summarization is already enabled (model: %s).\n", cfg.Summarization.Model))
			return nil
		}
		cfg.Summarization.Enabled = true
		if err := config.Save(cfg); err != nil {
			return fmt.Errorf("failed to save config: %w", err)
		}
		fmt.Print(thinktI18n.Tf("indexer.summarize.enabled", "Summarization enabled (model: %s).\n", cfg.Summarization.Model))
		notifyServerConfigReload()
		return nil
	},
}

var summarizeDisableCmd = &cobra.Command{
	Use:   "disable",
	Short: "Disable summarization",
	Args:  cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		cfg, err := config.Load()
		if err != nil {
			cfg = config.Default()
		}
		if !cfg.Summarization.Enabled {
			fmt.Println(thinktI18n.T("indexer.summarize.alreadyDisabled", "Summarization is already disabled."))
			return nil
		}
		cfg.Summarization.Enabled = false
		if err := config.Save(cfg); err != nil {
			return fmt.Errorf("failed to save config: %w", err)
		}
		fmt.Println(thinktI18n.T("indexer.summarize.disabled", "Summarization disabled."))
		notifyServerConfigReload()
		return nil
	},
}

var summarizeModelCmd = &cobra.Command{
	Use:   "model [model-id]",
	Short: "Switch the summarization model",
	Long: `Switch to a different summarization model.

Without arguments, opens an interactive picker.
With an argument, switches directly to the specified model.`,
	Args: cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		cfg, err := config.Load()
		if err != nil {
			cfg = config.Default()
		}

		var newModel string
		if len(args) > 0 {
			newModel = args[0]
		} else {
			if !isTTY() {
				return fmt.Errorf("%s", thinktI18n.T("indexer.summarize.model.noTerminal", "interactive model picker requires a terminal; pass model ID as argument"))
			}
			selected, err := pickSummarizeModel(cfg.Summarization.Model)
			if err != nil {
				return err
			}
			if selected == nil {
				return nil // cancelled
			}
			newModel = *selected
		}
		if _, err := summarize.LookupModel(newModel); err != nil {
			fmt.Fprint(os.Stderr, thinktI18n.Tf("indexer.summarize.model.unknown", "Unknown model %q. Available models:\n\n", newModel))
			printSummarizeModelList(cfg.Summarization.Model)
			return fmt.Errorf("unknown model %q", newModel)
		}

		if cfg.Summarization.Model == newModel {
			fmt.Print(thinktI18n.Tf("indexer.summarize.model.alreadyUsing", "Already using %s.\n", newModel))
			return nil
		}

		old := cfg.Summarization.Model
		cfg.Summarization.Model = newModel
		if err := config.Save(cfg); err != nil {
			return fmt.Errorf("failed to save config: %w", err)
		}

		fmt.Print(thinktI18n.Tf("indexer.summarize.model.switched", "Switched summarization model: %s → %s\n", old, newModel))
		if cfg.Summarization.Enabled {
			fmt.Println(thinktI18n.T("indexer.summarize.model.downloadHint", "The model will be downloaded on next sync if needed."))
			notifyServerConfigReload()
		}
		return nil
	},
	ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		if len(args) > 0 {
			return nil, cobra.ShellCompDirectiveNoFileComp
		}
		var ids []string
		for id := range summarize.KnownModels {
			ids = append(ids, id)
		}
		sort.Strings(ids)
		return ids, cobra.ShellCompDirectiveNoFileComp
	},
}

func printSummarizeModelList(activeModel string) {
	ids := make([]string, 0, len(summarize.KnownModels))
	for id := range summarize.KnownModels {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	// Gather per-model summary stats from DB files.
	sumStats := make(map[string]summaryModelStats)
	if files, err := filepath.Glob(filepath.Join(sumDBDir, "*.duckdb")); err == nil {
		for _, f := range files {
			fi, err := os.Stat(f)
			if err != nil {
				continue
			}
			mID := strings.TrimSuffix(filepath.Base(f), ".duckdb")
			if sDB, err := db.OpenReadOnly(f); err == nil {
				var count, sessions int
				_ = sDB.QueryRow("SELECT count(*), count(DISTINCT session_id) FROM summaries").Scan(&count, &sessions)
				sumStats[mID] = summaryModelStats{
					Count:    count,
					Sessions: sessions,
					Size:     fi.Size(),
				}
				sDB.Close()
			}
		}
	}

	t := theme.Current()
	headerStyle := lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(t.GetAccent()))
	primaryStyle := lipgloss.NewStyle().Foreground(lipgloss.Color(t.TextPrimary.Fg))
	secondaryStyle := lipgloss.NewStyle().Foreground(lipgloss.Color(t.TextSecondary.Fg))
	mutedStyle := lipgloss.NewStyle().Foreground(lipgloss.Color(t.TextMuted.Fg))
	accentStyle := lipgloss.NewStyle().Foreground(lipgloss.Color(t.GetAccent()))

	const gap = 2
	notDownloaded := thinktI18n.T("indexer.summarize.notDownloaded", "not downloaded")
	colModel, colCtx, colSize, colSess := 5, 7, len(notDownloaded), 8
	for _, id := range ids {
		if len(id) > colModel {
			colModel = len(id)
		}
		spec := summarize.KnownModels[id]
		if d := len(fmt.Sprintf("%d", spec.NCtx)); d > colCtx {
			colCtx = d
		}
	}
	colModel += gap + 2 // +2 for "* " marker prefix
	colCtx += gap
	colSize += gap
	colSess += gap

	col := func(s lipgloss.Style, w int) lipgloss.Style { return s.Width(w) }

	fmt.Fprintf(os.Stdout, "  %s%s%s%s%s\n",
		col(headerStyle, colModel).Render(thinktI18n.T("indexer.summarize.header.model", "MODEL")),
		col(headerStyle, colCtx).Render(thinktI18n.T("indexer.summarize.header.ctx", "CTX")),
		col(headerStyle, colSize).Render(thinktI18n.T("indexer.summarize.header.modelSize", "MODEL SIZE")),
		col(headerStyle, colSess).Render(thinktI18n.T("indexer.summarize.header.sessions", "SESSIONS")),
		headerStyle.Render(thinktI18n.T("indexer.summarize.header.dbSize", "DB SIZE")),
	)

	for _, id := range ids {
		spec := summarize.KnownModels[id]

		modelSize := col(mutedStyle, colSize).Render(thinktI18n.T("indexer.summarize.notDownloaded", "not downloaded"))
		if size := summarizeModelFileSize(id); size >= 0 {
			modelSize = col(secondaryStyle, colSize).Render(formatBytes(size))
		}

		sessionCol := col(mutedStyle, colSess).Render("-")
		dbSizeCol := mutedStyle.Render("-")
		if st, ok := sumStats[id]; ok && st.Count > 0 {
			sessionCol = col(secondaryStyle, colSess).Render(fmt.Sprintf("%d", st.Sessions))
			dbSizeCol = secondaryStyle.Render(formatBytes(st.Size))
		}

		marker := " "
		nameStyle := primaryStyle
		if id == activeModel {
			marker = accentStyle.Render("*")
			nameStyle = accentStyle.Bold(true)
		}
		fmt.Fprintf(os.Stdout, "%s %s%s%s%s%s\n",
			marker,
			col(nameStyle, colModel).Render(id),
			col(secondaryStyle, colCtx).Render(fmt.Sprintf("%d", spec.NCtx)),
			modelSize,
			sessionCol,
			dbSizeCol)
	}
}

func summarizeModelFileSize(modelID string) int64 {
	p, err := summarize.ModelPathForID(modelID)
	if err != nil {
		return -1
	}
	fi, err := os.Stat(p)
	if err != nil {
		return -1
	}
	return fi.Size()
}

func pickSummarizeModel(activeModel string) (*string, error) {
	ids := make([]string, 0, len(summarize.KnownModels))
	for id := range summarize.KnownModels {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	var options []tui.ModelOption
	for _, id := range ids {
		spec := summarize.KnownModels[id]
		options = append(options, tui.ModelOption{
			ID:     id,
			Detail: fmt.Sprintf("%d ctx", spec.NCtx),
			Active: id == activeModel,
		})
	}

	return tui.PickModel(options)
}

func printSummarizeModelListJSON(activeModel string) error {
	ids := make([]string, 0, len(summarize.KnownModels))
	for id := range summarize.KnownModels {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	type modelInfo struct {
		ID         string `json:"id"`
		NCtx       uint32 `json:"n_ctx"`
		Active     bool   `json:"active"`
		Downloaded bool   `json:"downloaded"`
		SizeBytes  int64  `json:"size_bytes,omitempty"`
	}

	var models []modelInfo
	for _, id := range ids {
		spec := summarize.KnownModels[id]
		m := modelInfo{
			ID:     id,
			NCtx:   spec.NCtx,
			Active: id == activeModel,
		}
		if size := summarizeModelFileSize(id); size >= 0 {
			m.Downloaded = true
			m.SizeBytes = size
		}
		models = append(models, m)
	}

	return json.NewEncoder(os.Stdout).Encode(map[string]any{
		"active": activeModel,
		"models": models,
	})
}

type summaryModelStats struct {
	Model    string `json:"model"`
	Count    int    `json:"count"`
	Sessions int    `json:"sessions"`
	Size     int64  `json:"size_bytes"`
}

var summarizeStatusJSON bool

var summarizeStatusCmd = &cobra.Command{
	Use:   "status",
	Short: "Show summarization configuration and status",
	Args:  cobra.NoArgs,
	RunE: func(cmdObj *cobra.Command, args []string) error {
		cfg, err := config.Load()
		if err != nil {
			cfg = config.Default()
		}

		modelID := cfg.Summarization.Model
		spec, _ := summarize.LookupModel(modelID)
		modelPath, _ := summarize.ModelPathForID(modelID)
		_, statErr := os.Stat(modelPath)
		modelDownloaded := statErr == nil

		// Summary stats for active model from DB
		var activeStats summaryModelStats
		var categoryBreakdown map[string]int
		sumPath := db.SummariesPathForModel(sumDBDir, modelID)
		if fi, err := os.Stat(sumPath); err == nil {
			activeStats.Size = fi.Size()
			if sumDB, err := db.OpenReadOnly(sumPath); err == nil {
				_ = sumDB.QueryRow("SELECT count(*), count(DISTINCT session_id) FROM summaries").Scan(&activeStats.Count, &activeStats.Sessions)
				rows, err := sumDB.Query("SELECT COALESCE(category, 'session'), count(*) FROM summaries GROUP BY category")
				if err == nil {
					categoryBreakdown = make(map[string]int)
					for rows.Next() {
						var cat string
						var cnt int
						if rows.Scan(&cat, &cnt) == nil {
							categoryBreakdown[cat] = cnt
						}
					}
					rows.Close()
				}
				sumDB.Close()
			}
		}

		if summarizeStatusJSON {
			out := map[string]any{
				"enabled":          cfg.Summarization.Enabled,
				"model":            modelID,
				"model_ctx":        spec.NCtx,
				"model_downloaded": modelDownloaded,
				"summaries":        activeStats.Count,
				"sessions":         activeStats.Sessions,
				"db_size_bytes":    activeStats.Size,
			}
			if categoryBreakdown != nil {
				out["categories"] = categoryBreakdown
			}
			return json.NewEncoder(os.Stdout).Encode(out)
		}

		t := theme.Current()
		labelStyle := lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(t.GetAccent()))
		valueStyle := lipgloss.NewStyle().Foreground(lipgloss.Color(t.TextPrimary.Fg))
		mutedVal := lipgloss.NewStyle().Foreground(lipgloss.Color(t.TextMuted.Fg))
		accentVal := lipgloss.NewStyle().Foreground(lipgloss.Color(t.GetAccent()))
		secondaryVal := lipgloss.NewStyle().Foreground(lipgloss.Color(t.TextSecondary.Fg))

		colLabel := 16 + 2 // "Summarization:" is longest label + gap
		col := func(s lipgloss.Style, w int) lipgloss.Style { return s.Width(w) }

		enabled := mutedVal.Render(thinktI18n.T("common.status.disabled", "disabled"))
		if cfg.Summarization.Enabled {
			enabled = accentVal.Render(thinktI18n.T("common.status.enabled", "enabled"))
		}
		download := mutedVal.Render(thinktI18n.T("indexer.summarize.notDownloaded", "not downloaded"))
		if modelDownloaded {
			download = accentVal.Render(thinktI18n.T("indexer.summarize.status.ready", "ready"))
		}

		fmt.Fprintf(os.Stdout, "%s%s\n", col(labelStyle, colLabel).Render(thinktI18n.T("indexer.summarize.status.summarizationLabel", "Summarization:")), enabled)
		fmt.Fprintf(os.Stdout, "%s%s\n", col(labelStyle, colLabel).Render(thinktI18n.T("indexer.summarize.status.modelLabel", "Model:")), valueStyle.Render(fmt.Sprintf("%s (%d ctx)", modelID, spec.NCtx)))
		fmt.Fprintf(os.Stdout, "%s%s\n", col(labelStyle, colLabel).Render(thinktI18n.T("indexer.summarize.status.downloadLabel", "Download:")), download)
		if activeStats.Count == 0 {
			fmt.Fprintf(os.Stdout, "%s%s\n", col(labelStyle, colLabel).Render(thinktI18n.T("indexer.summarize.status.storedLabel", "Stored:")), mutedVal.Render(thinktI18n.T("indexer.summarize.status.zeroSummaries", "0 summaries")))
		} else {
			stored := thinktI18n.Tf("indexer.summarize.status.storedCount", "%d summaries across %d sessions", activeStats.Count, activeStats.Sessions)
			if activeStats.Size > 0 {
				stored += fmt.Sprintf(" (%s)", formatBytes(activeStats.Size))
			}
			fmt.Fprintf(os.Stdout, "%s%s\n", col(labelStyle, colLabel).Render(thinktI18n.T("indexer.summarize.status.storedLabel", "Stored:")), valueStyle.Render(stored))
			if categoryBreakdown != nil {
				// Sort category names for stable output.
				cats := make([]string, 0, len(categoryBreakdown))
				for cat := range categoryBreakdown {
					cats = append(cats, cat)
				}
				sort.Strings(cats)
				for _, cat := range cats {
					fmt.Fprintf(os.Stdout, " %s%s\n", col(secondaryVal, colLabel-1).Render(cat+":"), secondaryVal.Render(fmt.Sprintf("%d", categoryBreakdown[cat])))
				}
			}
		}

		return nil
	},
}

// summarizeSyncProgress is the union of ModelDownloadProgressData and SummarizeProgressData
// fields, used to unmarshal streaming RPC progress events.
type summarizeSyncProgress struct {
	ModelDownload bool    `json:"model_download"`
	Percent       float64 `json:"percent"`
	Downloaded    int64   `json:"downloaded"`
	Total         int64   `json:"total"`
	Done          int     `json:"done"`
	SessionID     string  `json:"session_id"`
	ElapsedMs     int64   `json:"elapsed_ms"`
}

var summarizeSyncCmd = &cobra.Command{
	Use:   "sync",
	Short: "Run summarization sync (download model if needed, summarize all sessions)",
	Args:  cobra.NoArgs,
	RunE: func(cmdObj *cobra.Command, args []string) error {
		cfg, err := config.Load()
		if err != nil {
			cfg = config.Default()
		}

		// Try RPC first (server holds the DB lock).
		if rpc.ServerAvailable() {
			sp := NewSyncProgress()
			var progressFn func(rpc.Progress)
			if sp.ShouldShowProgress(quiet, verbose) {
				progressFn = func(p rpc.Progress) {
					var data summarizeSyncProgress
					if err := json.Unmarshal(p.Data, &data); err == nil {
						if data.ModelDownload {
							pct := data.Percent / 100
							detail := fmt.Sprintf("%s / %s  %.0f%%", formatBytes(data.Downloaded), formatBytes(data.Total), data.Percent)
							if sp.IsTTY() {
								sp.RenderLine(thinktI18n.T("indexer.progress.download", "Download"), cfg.Summarization.Model, detail, pct)
							} else {
								sp.Print(thinktI18n.Tf("indexer.progress.downloading", "Downloading %s: %.0f%%", cfg.Summarization.Model, data.Percent))
							}
						} else if data.Done > 0 || data.Total > 0 {
							sid := data.SessionID
							if len(sid) > 8 {
								sid = sid[:8]
							}
							elapsed := time.Duration(data.ElapsedMs) * time.Millisecond
							detail := fmt.Sprintf("%s (%s)", sid, elapsed.Round(time.Millisecond))
							sp.RenderEmbedding(data.Done, int(data.Total), detail)
						}
					}
				}
			}
			resp, err := rpc.Call(rpc.MethodSummarizeSync, rpc.SummarizeSyncParams{}, progressFn)
			if err != nil {
				if sp.ShouldShowProgress(quiet, verbose) {
					sp.Finish()
				}
				fmt.Fprint(os.Stderr, thinktI18n.Tf("indexer.summarize.sync.rpcFallback", "RPC summarize_sync failed, falling back to inline: %v\n", err))
			} else if !resp.OK {
				if sp.ShouldShowProgress(quiet, verbose) {
					sp.Finish()
				}
				return fmt.Errorf("summarize_sync: %s", resp.Error)
			} else {
				if sp.ShouldShowProgress(quiet, verbose) {
					sp.Finish()
				}
				if !quiet {
					fmt.Println(thinktI18n.T("indexer.summarize.sync.completeViaServer", "Summarization sync complete (via server)."))
				}
				return nil
			}
		}

		// Inline fallback.

		if !cfg.Summarization.Enabled {
			return fmt.Errorf("%s", thinktI18n.T("indexer.summarize.sync.notEnabled", "summarization is not enabled (run: thinkt-indexer summarize enable)"))
		}

		modelID := cfg.Summarization.Model

		// Download model if needed.
		dlSp := NewSyncProgress()
		if err := summarize.EnsureModel(modelID, func(downloaded, total int64) {
			if total > 0 && dlSp.ShouldShowProgress(quiet, verbose) {
				pct := float64(downloaded) / float64(total)
				detail := fmt.Sprintf("%s / %s  %.0f%%", formatBytes(downloaded), formatBytes(total), pct*100)
				if dlSp.IsTTY() {
					dlSp.RenderLine(thinktI18n.T("indexer.progress.download", "Download"), modelID, detail, pct)
				} else {
					dlSp.Print(thinktI18n.Tf("indexer.progress.downloading", "Downloading %s: %.0f%%", modelID, pct*100))
				}
			}
		}); err != nil {
			return fmt.Errorf("failed to download summarization model: %w", err)
		}
		if dlSp.ShouldShowProgress(quiet, verbose) {
			dlSp.Finish()
		}

		// Create summarizer.
		summarizer, err := summarize.NewSummarizer(modelID, "")
		if err != nil {
			return fmt.Errorf("failed to create summarizer: %w", err)
		}
		defer summarizer.Close()

		// Open databases.
		database, err := getDB()
		if err != nil {
			return fmt.Errorf("%s", thinktI18n.T("indexer.summarize.sync.dbLocked", "index database is locked by another process (likely 'thinkt-indexer serve')"))
		}
		defer database.Close()

		sumDB, err := getSummariesDB(modelID)
		if err != nil {
			return fmt.Errorf("%s", thinktI18n.T("indexer.summarize.sync.sumDbLocked", "summaries database is locked by another process"))
		}
		defer sumDB.Close()

		registry := cmd.CreateSourceRegistryFiltered(cfg.Indexer.Sources)
		ingester := indexer.NewIngester(database, nil, sumDB, registry, nil, summarizer)
		ingester.Verbose = verbose

		ctx := context.Background()

		sp := NewSyncProgress()
		if sp.ShouldShowProgress(quiet, verbose) {
			ingester.OnSummarizeProgress = func(done, total int, sessionID string, elapsed time.Duration) {
				sid := sessionID[:min(8, len(sessionID))]
				detail := fmt.Sprintf("%s (%s)", sid, elapsed.Round(time.Millisecond))
				sp.RenderEmbedding(done, total, detail)
			}
		}

		if err := ingester.SummarizeAllSessions(ctx); err != nil {
			return fmt.Errorf("summarization error: %w", err)
		}

		if sp.ShouldShowProgress(quiet, verbose) {
			sp.Finish()
		}

		if !quiet {
			fmt.Println(thinktI18n.T("indexer.summarize.sync.complete", "Summarization sync complete."))
		}
		return nil
	},
}

var summarizeRunJSON bool
var summarizeTagsJSON bool

func readSummarizeInput(args []string) (string, error) {
	if len(args) == 1 {
		return strings.TrimSpace(args[0]), nil
	}
	if !term.IsTerminal(int(os.Stdin.Fd())) {
		data, err := io.ReadAll(os.Stdin)
		if err != nil {
			return "", fmt.Errorf("read stdin: %w", err)
		}
		return strings.TrimSpace(string(data)), nil
	}
	return "", fmt.Errorf("provide text as an argument or pipe via stdin")
}

func newLocalSummarizer() (*summarize.Summarizer, error) {
	cfg, err := config.Load()
	if err != nil {
		cfg = config.Default()
	}
	modelID := cfg.Summarization.Model

	if err := summarize.EnsureModel(modelID, nil); err != nil {
		return nil, fmt.Errorf("model not available: %w (run: thinkt-indexer summarize sync)", err)
	}

	s, err := summarize.NewSummarizer(modelID, "")
	if err != nil {
		return nil, fmt.Errorf("failed to create summarizer: %w", err)
	}
	return s, nil
}

var suggestTagsForInput = func(ctx context.Context, input string) (*summarize.TagSuggestionResult, error) {
	s, err := newLocalSummarizer()
	if err != nil {
		return nil, err
	}
	defer s.Close()
	return s.SuggestTags(ctx, input)
}

var summarizeRunCmd = &cobra.Command{
	Use:   "run [text]",
	Short: "Summarize and classify a thinking block",
	Long: `Summarize and classify a thinking block using the local summarization model.

Provide text as a positional argument, or pipe input via stdin.`,
	Args: cobra.MaximumNArgs(1),
	RunE: func(cmdObj *cobra.Command, args []string) error {
		input, err := readSummarizeInput(args)
		if err != nil {
			return err
		}
		if input == "" {
			return fmt.Errorf("empty input")
		}

		s, err := newLocalSummarizer()
		if err != nil {
			return err
		}
		defer s.Close()

		result, err := s.Summarize(context.Background(), input)
		if err != nil {
			return fmt.Errorf("summarize: %w", err)
		}

		if summarizeRunJSON {
			enc := json.NewEncoder(os.Stdout)
			enc.SetIndent("", "  ")
			return enc.Encode(result)
		}

		fmt.Printf("Summary:   %s\n", result.Summary)
		fmt.Printf("Category:  %s\n", result.Category)
		if len(result.Entities) > 0 {
			fmt.Printf("Entities:  %s\n", strings.Join(result.Entities, ", "))
		}
		fmt.Printf("Relevance: %.2f\n", result.Relevance)
		return nil
	},
}

var summarizeTagsCmd = &cobra.Command{
	Use:   "tags [text]",
	Short: "Suggest shareable tags for a thinking block",
	Long: `Suggest shareable tags for a thinking block using the local summarization model.

Provide text as a positional argument, or pipe input via stdin.`,
	Args: cobra.MaximumNArgs(1),
	RunE: func(cmdObj *cobra.Command, args []string) error {
		input, err := readSummarizeInput(args)
		if err != nil {
			return err
		}
		if input == "" {
			return fmt.Errorf("empty input")
		}

		result, err := suggestTagsForInput(context.Background(), input)
		if err != nil {
			return fmt.Errorf("suggest tags: %w", err)
		}

		if summarizeTagsJSON {
			enc := json.NewEncoder(cmdObj.OutOrStdout())
			enc.SetIndent("", "  ")
			return enc.Encode(result)
		}

		fmt.Fprintf(cmdObj.OutOrStdout(), "Tags:       %s\n", strings.Join(result.Tags, ", "))
		fmt.Fprintf(cmdObj.OutOrStdout(), "Confidence: %.2f\n", result.Confidence)
		return nil
	},
}

func init() {
	summarizeCmd.Flags().BoolVar(&summarizeListJSON, "json", false, "Output as JSON")
	summarizeListCmd.Flags().BoolVar(&summarizeListJSON, "json", false, "Output as JSON")
	summarizeCmd.AddCommand(summarizeListCmd)
	summarizeCmd.AddCommand(summarizePurgeCmd)
	summarizeCmd.AddCommand(summarizeEnableCmd)
	summarizeCmd.AddCommand(summarizeDisableCmd)
	summarizeCmd.AddCommand(summarizeModelCmd)
	summarizeStatusCmd.Flags().BoolVar(&summarizeStatusJSON, "json", false, "Output as JSON")
	summarizeCmd.AddCommand(summarizeStatusCmd)
	summarizeCmd.AddCommand(summarizeSyncCmd)
	summarizeRunCmd.Flags().BoolVar(&summarizeRunJSON, "json", false, "Output as JSON")
	summarizeCmd.AddCommand(summarizeRunCmd)
	summarizeTagsCmd.Flags().BoolVar(&summarizeTagsJSON, "json", false, "Output as JSON")
	summarizeCmd.AddCommand(summarizeTagsCmd)
	rootCmd.AddCommand(summarizeCmd)
}
